### ISSUE TITLE
Unable to build aot

### ISSUE THREAD

**Issue by vatsalpande** [seanlandsman/webpack-ngtools-blog#1]
Hi,

Not sure if I am missing anything, but I just downloaded the project, did npm install and executed 

> npm run build:aot

It gives me an error saying 

> Can't resolve '../aot/app/app.module.ngfactory'

I am definitely missing something. Can you please help?

Thanks,
Vatsal

**Comment by ja6a** [comment]
I am also getting this issue. Is it connected with [https://github.com/angular/angular-cli/issues/7540](https://github.com/angular/angular-cli/issues/7540)?

`root@fb254e4b2d6c:/# node -v
v8.5.0
root@fb254e4b2d6c:/# npm -v
5.3.0`
Stacktrace:
`npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @ngtools/webpack@1.2.8 requires a peer of webpack@2.2.0 but none was installed.
npm WARN url-loader@0.5.7 requires a peer of file-loader@* but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 570 packages in 51.42s
root@fb254e4b2d6c:~/webpack-ngtools-blog# npm run build:aot

> ag-grid-angular-example@8.2.0 build:aot /root/webpack-ngtools-blog
> npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail


> ag-grid-angular-example@8.2.0 clean-aot /root/webpack-ngtools-blog
> rimraf dist/aot/*

 10% building modules 3/3 modules 0 activeError                                    
    at factoryCallback (/root/webpack-ngtools-blog/node_modules/webpack/lib/Compilation.js:259:39)
    at /root/webpack-ngtools-blog/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/root/webpack-ngtools-blog/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /root/webpack-ngtools-blog/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /root/webpack-ngtools-blog/node_modules/async/dist/async.js:3861:9
    at /root/webpack-ngtools-blog/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/root/webpack-ngtools-blog/node_modules/async/dist/async.js:996:13)
    at /root/webpack-ngtools-blog/node_modules/async/dist/async.js:906:16
    at /root/webpack-ngtools-blog/node_modules/async/dist/async.js:3858:13
    at /root/webpack-ngtools-blog/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onError (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/root/webpack-ngtools-blog/node_modules/tapable/lib/Tapable.js:252:11)
    at /root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/root/webpack-ngtools-blog/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/root/webpack-ngtools-blog/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:168:10)
    at loggingCallbackWrapper (/root/webpack-ngtools-blog/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/root/webpack-ngtools-blog/node_modules/tapable/lib/Tapable.js:252:11)
resolve '../aot/app/app.module.ngfactory' in '/root/webpack-ngtools-blog/app'
  using description file: /root/webpack-ngtools-blog/package.json (relative path: ./app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /root/webpack-ngtools-blog/package.json (relative path: ./app)
    using description file: /root/webpack-ngtools-blog/package.json (relative path: ./aot/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /root/webpack-ngtools-blog/aot/app/app.module.ngfactory doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /root/webpack-ngtools-blog/aot/app/app.module.ngfactory.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /root/webpack-ngtools-blog/aot/app/app.module.ngfactory.ts doesn't exist
      as directory
        /root/webpack-ngtools-blog/aot/app/app.module.ngfactory doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ag-grid-angular-example@8.2.0 build:aot: `npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ag-grid-angular-example@8.2.0 build:aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by ja6a** [comment]
I fixed it by following:
[https://github.com/angular/angular-cli/issues/7113](https://github.com/angular/angular-cli/issues/7113).

I bumped:
"webpack": "3.3.x"
"@ngtools/webpack": "1.6.2"
I added to dependencies:
"enhanced-resolve": "3.3.0"
